services:
  frontend:
    image: bcdmusic-frontend:latest
    container_name: bcdmusic-frontend
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - bcdmusic-network

networks:
  bcdmusic-network:
    driver: bridge