version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: bcdmusic-frontend
    ports:
      - "80:3000"
    restart: unless-stopped
    networks:
      - bcdmusic-network

networks:
  bcdmusic-network:
    driver: bridge